### ISSUE TITLE
Syntax error on october cms marketplace

### ISSUE THREAD

**Issue by hostia-ug** [Samuell1/contenteditor-plugin#120]
![image](https://user-images.githubusercontent.com/83402258/206807291-ef23b114-dd8d-4715-8b48-346871d8ede6.png)

Hi, this is the same error as #119. I think the marketplace version is not up to date.

**Comment by samuelpatro** [comment]
Hey, i pushed a new version to fix this issue.

**Comment by PubliAlex** [comment]
Hello, just installed a new instance of october 3, still have the issue. Are you sure you updated your plugin on the october cms website ?
